from models.custom.bottleneck import BOTTLENECK_CLASS_DICT, BOTTLENECK_FUNC_DICT

CUSTOM_MODEL_CLASS_DICT = dict()
CUSTOM_MODEL_FUNC_DICT = dict()

CUSTOM_MODEL_CLASS_DICT.update(BOTTLENECK_CLASS_DICT)
CUSTOM_MODEL_FUNC_DICT.update(BOTTLENECK_FUNC_DICT)
