dependencies:
  - name: 'custom'

datasets:
  glue:
    name: &dataset_name 'cola'
    raw_data_kwargs:
      train_file_path:
      valid_file_path:
    dataset_id_map:
      train: &glue_train !join [*dataset_name, '/train']
      validation: &glue_val !join [*dataset_name, '/val']
      test: &glue_test !join [*dataset_name, '/test']

models:
  teacher_model:
    key: &teacher_model_key 'bert-large-uncased'
    model_name_or_path: &teacher_model_path 'yoshitomo-matsubara/bert-large-uncased-cola'
    config_kwargs:
      pretrained_model_name_or_path: *teacher_model_path
      num_labels: 2
    tokenizer_kwargs:
      pretrained_model_name_or_path: *teacher_model_path
      do_lower: True
      use_fast: True
    model_kwargs:
      pretrained_model_name_or_path: *teacher_model_path
  student_model:
    key: &student_model_key 'bert-base-uncased'
    model_name_or_path: *student_model_key
    config_kwargs:
      pretrained_model_name_or_path: *student_model_key
      num_labels: 2
    tokenizer_kwargs:
      pretrained_model_name_or_path: *student_model_key
      do_lower: True
      use_fast: True
    model_kwargs:
      pretrained_model_name_or_path: *student_model_key
    _experiment: &student_experiment !join [*dataset_name, '-', *student_model_key, '_from_', *teacher_model_key]
    src_ckpt:
    dst_ckpt: !join ['./resource/ckpt/glue/', *dataset_name, '/kd/', *student_experiment]

train:
  log_freq: 50
  num_epochs: 3
  train_data_loader:
    dataset_id: *glue_train
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.RandomSampler'
      kwargs:
    kwargs:
      batch_size: 16
      num_workers: 0
      pin_memory: True
      drop_last: False
    collate_fn: 'DataCollatorWithPadding'
    requires_supp: False
    cache_output:
  val_data_loader:
    dataset_id: *glue_val
    sampler: &val_sampler
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    kwargs:
      batch_size: 32
      num_workers: 0
      pin_memory: True
      drop_last: False
    collate_fn: 'DataCollatorWithPadding'
    requires_supp: False
  teacher:
    forward_proc: 'forward_batch_as_kwargs'
    adaptations:
    sequential: []
    wrapper:
    requires_grad: False
    frozen_modules: []
    forward_hook:
      input: []
      output: ['classifier']
  student:
    forward_proc: 'forward_batch_as_kwargs'
    adaptations:
    sequential: []
    wrapper:
    requires_grad: True
    frozen_modules: []
    forward_hook:
      input: []
      output: ['classifier']
  optimizer:
    key: 'optimizer_no_decay'
    kwargs:
      optimizer_key: 'AdamW'
      lr: 1.0e-4
      weight_decay: 0.0
    filters_params: False
    max_grad_norm: 1.0
    grad_accum_step: 1
  scheduler:
    key: 'get_linear_schedule_with_warmup'
    kwargs:
      num_warmup_steps: 0
      num_training_steps:
    scheduling_step: 1
  criterion:
    key: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        kd:
          criterion:
            key: 'KDLoss'
            kwargs:
              student_module_path: 'classifier'
              student_module_io: 'output'
              teacher_module_path: 'classifier'
              teacher_module_io: 'output'
              temperature: 7.0
              alpha: 0.9
              reduction: 'batchmean'
          weight: 1.0

test:
  test_data_loader:
    dataset_id: *glue_val
    sampler: *val_sampler
    kwargs:
      batch_size: 32
      num_workers: 0
      pin_memory: True
      drop_last: False
    collate_fn: 'DataCollatorWithPadding'

private:
  - private_data_loader:
      dataset_id: *glue_test
      task_name: cola
      sampler: *val_sampler
      kwargs:
        batch_size: 32
        num_workers: 0
        pin_memory: True
        drop_last: False
      collate_fn: 'DataCollatorWithPadding'
    idx2str: False
    pred_output: 'CoLA.tsv'
