from .registry import ADAPTATION_CLASS_DICT, SPECIAL_CLASS_DICT
from .classification import CLASSIFICATION_MODEL_FUNC_DICT
from .custom import CUSTOM_MODEL_CLASS_DICT, CUSTOM_MODEL_FUNC_DICT

MODEL_DICT = dict()

MODEL_DICT.update(ADAPTATION_CLASS_DICT)
MODEL_DICT.update(SPECIAL_CLASS_DICT)
MODEL_DICT.update(CUSTOM_MODEL_CLASS_DICT)
MODEL_DICT.update(CUSTOM_MODEL_FUNC_DICT)
MODEL_DICT.update(CLASSIFICATION_MODEL_FUNC_DICT)
