from .registry import ADAPTATION_MODULE_DICT, AUXILIARY_MODEL_WRAPPER_DICT
from .classification import CLASSIFICATION_MODEL_FUNC_DICT
from .custom import CUSTOM_MODEL_CLASS_DICT, CUSTOM_MODEL_FUNC_DICT

MODEL_DICT = dict()

MODEL_DICT.update(ADAPTATION_MODULE_DICT)
MODEL_DICT.update(AUXILIARY_MODEL_WRAPPER_DICT)
MODEL_DICT.update(CUSTOM_MODEL_CLASS_DICT)
MODEL_DICT.update(CUSTOM_MODEL_FUNC_DICT)
MODEL_DICT.update(CLASSIFICATION_MODEL_FUNC_DICT)
